global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mystrom
    scrape_interval: 3s
    metrics_path: /device
    honor_labels: true
    static_configs:
      - targets:
          - "192.168.1.19"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: mystrom-exporter:9452
remote_write:
  - url: "http://192.168.1.121:9090/api/v1/write"
